version: '3.9'

volumes:
  pgdata:
  static_volume:

networks:
  backend:


services:
  python_app:
    build: .
    networks:
      - backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgredb
    command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000

  postgredb:
    image: postgres:latest
    networks:
      - backend
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2022
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d my_db"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    volumes:
      - .:/logs:/var/log
      - pgdata:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.b

  nginx:
    build: ./nginx
    networks:
      - backend
    volumes:
      - .:/app/python_app
    ports:
      - "1337:80"
    links:
      - python_app:python_app
    depends_on:
      - python_app